### ISSUE TITLE
Support JS/web for Apple Sign In

### ISSUE THREAD

**Issue by mlynch** [capacitor-community/apple-sign-in#1]
Apple supports Sign in with Apple on the web. This would fit naturally into the web side of this plugin: 

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple

Would love some help making this happen! I think we'd need an `init` method and also some extra options to the `Authorize` call to support the fields needed on the JS side.

**Comment by carsten-klaffke** [comment]
Hello! Whats the status of the web/Android implementation? I would need this and would give it a try. Is there already some some progress to build up from?

**Comment by dwieeb** [comment]
@carsten-klaffke The web implementation is near completion in [this PR](https://github.com/capacitor-community/apple-sign-in/pull/2). The Android implementation has not begun as far as I know.

**Comment by carsten-klaffke** [comment]
Great! I will try out the web implementation and see what I can do on android.

**Comment by chrisweight** [comment]
@mlynch quick bump on this...

**Comment by chrisweight** [comment]
@mlynch - looks like @epicshaggy merged in #18 already, this can probably be closed if it's verified as working.

**Comment by joseph-navant** [comment]
Hi! I'm using the v1.0.0 version of this plugin on Ionic project and I'm getting a "SignInWithApple does not have web implementation." error when I call `SignInWithApple.authorize()`. I served mi project using `ionic serve`. Thanks in advance.
