### ISSUE TITLE
Sign-in hangs on iOS 14

### ISSUE THREAD

**Issue by askilondz** [capacitor-community/apple-sign-in#10]
**Describe the bug**
This only appears to be happening on the simulators. After authorizing my apple credentials the spinner hangs and nothing happens. Apple keeps rejecting my app because of this otherwise I wouldn't be too concerned about it.

Test on simulator. Tried with capacitor `2.2.1` and `2.4.2`

**Comment by askilondz** [comment]
My apologies. This was an issue on my end. Sign in works fine on iOS 14 in the simulator.

**Comment by himanshusukhpal** [comment]
Can you tell how you fixed it, I too am facing the same problem and have switched to iOS 13 on the simulator, on which it works fine, but Apple is rejecting the submitted binaries.

**Comment by raykin** [comment]
Same here. iOS13 simulator works but 14 fails.
