### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by gasci** [capacitor-community/apple-sign-in#109]
Android SDK 34+ will be mandatory after August 2024. Do you have plans to upgrade this plugin?

**Comment by cschoenecker** [comment]
Same for me.. Capacitor 6 support needed

**Comment by Hambat** [comment]
++ Update please

**Comment by will-summerlin** [comment]
https://forum.ionicframework.com/t/apple-sign-in-not-working-in-simulator-and-real-device-but-works-in-browser/240952 pretty sure support is not continuing on this plugin

**Comment by gasci** [comment]
Oh, that is sad. What is the a actual alternative without using firebase?

**Comment by gasci** [comment]
The updates should be quite simple for this SDK update, though since it mostly concerns Android.

**Comment by bboldi** [comment]
There's a pull request for this, not sure what the status is

https://github.com/capacitor-community/apple-sign-in/pull/110

**Comment by yllaw** [comment]
I am more than happy to maintain this repo.

I kindly tagged some users who have write access in a comment in #110 asking for a merge and release - it was marked as abuse.

That being said I appreciate all of their hard work.

I also posted the PR in the Ionic discord community to see if it can gain any traction so hopefully it will.

**Comment by gasci** [comment]
I posted in the Discord channel.
![image](https://github.com/capacitor-community/apple-sign-in/assets/29505701/6156fbc0-8807-43b5-b94b-3547b95f6c1f)
