### ISSUE TITLE
Android and Web Implementation

### ISSUE THREAD

**Issue by epicshaggy** [capacitor-community/apple-sign-in#15]
I see there are pr's open for both of these, but they haven't been merged.  I'd like to know if they're going to be merged.  I could also work on the implementations if needed.

**Comment by dwieeb** [comment]
@epicshaggy Would you be able to join the [Capacitor contributor slack](https://getcapacitor.herokuapp.com/)?

**Comment by epicshaggy** [comment]
@dwieeb Yes, just joined!

**Comment by mesqueeb** [comment]
@dwieeb @epicshaggy any progress on this feature? I'd love to have it!

Also, once this feature is finished, maybe @baumblatt can use this plugin as a dependency? In order not to re-invent the wheel:
https://github.com/baumblatt/capacitor-firebase-auth

**Comment by epicshaggy** [comment]
@mesqueeb I worked on it but hit a road block.  I use Sign In With Apple for my job's app, for web and iOS I can use the plugin, but for Android I couldn't get the same behavior.  The idea of the implementation is that the plugin shouldn't care if you have your own backend service for authentication or if you use a third party service like Firebase, the plugin should only care about providing you with the `id_token` plus the extra information you request.  For iOS it's easy enough as the native framework returns this data.  For web it was a bit of problem figuring out how to get the data without a backend service but I managed to do it.  However for Android I couldn't find a way to return the data without assuming if you have a backend service or if you're using a third party service.  So I made a custom implementation separate from the plugin.  If anyone wants to give it a try they can contact me so I can share my research.

**Comment by mesqueeb** [comment]
@epicshaggy in this case can you try to make a PR that just adds support for the web version ?

Since this is the official capacitor plugin for apple Auth, i think a lot of ppl will appreciate that! < 3

Thank you so much for your contribution. The community thanks you.

**Comment by epicshaggy** [comment]
It has already been added in #2 and it's live on npm 😃

**Comment by mirko77** [comment]
@epicshaggy I'd like to try the Android implementation
