### ISSUE TITLE
Support iOS 12 and under

### ISSUE THREAD

**Issue by no-dap** [capacitor-community/apple-sign-in#16]
Related with #11

**Comment by mesqueeb** [comment]
I have the same issue.

**Comment by epicshaggy** [comment]
Have any of you guys worked on this?  I haven't tested if web implementation fixed this, I doubt it since it is using a pop up and I don't think WebView likes this.

**Comment by mesqueeb** [comment]
@epicshaggy i had the same issue for ios 12 i will test with your new v1 web view and let you know.

**Comment by mirko77** [comment]
web flow (usePopup) not working with WKWebView

**Comment by jcesarmobile** [comment]
version 4 has been published with Capacitor 4 support and requires iOS 13 as Capacitor 4, so this won't be implemented
