### ISSUE TITLE
Update this plugin for Capacitor 3

### ISSUE THREAD

**Issue by joseph-navant** [capacitor-community/apple-sign-in#22]
Capacitor 3 is being built and is already in [beta](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta). In this new version the native plugins have been removed from the core and there are some changes that are necessary in the existing plugins.

**Example: Plugin Imports**
The Plugins object is deprecated, but will continue to work in Capacitor 3. Capacitor plugins should be updated to use the new plugin registration APIs (see the Upgrade Guide for plugins), which will allow them to be imported directly from the plugin’s package.

Going forward, the Plugins object from @capacitor/core should not be used.

```
// OLD
import { Plugins } from '@capacitor/core';
const { AnyPlugin } = Plugins;
Importing the plugin directly from the plugin’s package is preferred, but the plugin must be updated to work with Capacitor 3 for this to be possible.
```

```
// NEW
import { AnyPlugin } from 'any-plugin';
```

**References:**

[Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/v3/updating/plugins/3-0)

[Updating Capacitor to 3.0 in your app](https://capacitorjs.com/docs/v3/updating/3-0)

(credits to @mklipe for issue explanation)

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by Linknpay** [comment]
any news please ?

**Comment by hatsantos** [comment]
The official Capacitor 3.0 was released.
I was checking my app, to see and update could be made and it seems this is the only plugin that is not yet compatible.

There's already an PR for this https://github.com/capacitor-community/apple-sign-in/pull/34 but is referring combability to Capacitor 3.0.0-beta.3. Don't know if it needs any additional change, assuming there's possible changes in the latest official release.

**Comment by Linknpay** [comment]
Hi, capacitor has launched their final release 3.0.0
Could you update the plugin because we are obtaining this error : 
```
Error: node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Type '{ [pluginName: string]: { [prop: string]: any; }; }' is missing the following properties from type 'PluginRegistry': SignInWithApple,
```

**Comment by vanessag** [comment]
Any update on if/when a capacitor 3 compatible release of this plugin will be available?

**Comment by patrickbussmann** [comment]
You must only install it without the tag.

```
npm install capacitor-community/apple-sign-in
```

Then you have the master branch installed and you can use with Capacitor 3.

**Comment by alexx855** [comment]
> npm install capacitor-community/apple-sign-in

![image](https://user-images.githubusercontent.com/1799851/121817964-b3400a00-cc84-11eb-98ab-8773f1912e20.png)

**Comment by selected-pixel-jameson** [comment]
@epicshaggy Why did you close this? It's still throwing the error @alexx855 posted.

**Comment by Off-Happy** [comment]
:(
