### ISSUE TITLE
version 1.0 breaking changes?

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/apple-sign-in#26]
I see that NPM is on version `v1.0`
The version here on Github is `v0.0.12`

I can't find any changelog / breaking changes for `v1.0`

I'd love to find some information on this!

**Comment by epicshaggy** [comment]
Thanks for letting me know, I'm not experienced with github.  I'll work on it!

**Comment by mesqueeb** [comment]
@epicshaggy this is a great release ! 
With this release: Is it possible to use the web integration for Android a well?
If it needs more tweaking to make it work: I'm thinking we can use in-app browser and deep links to go back to the app. What do you think ?

**Comment by mesqueeb** [comment]
I'll close the issue for cleaning purposes but let's keep the conversation going.

**Comment by epicshaggy** [comment]
@mesqueeb I didn't think of that, could try it out.  Also, you can checkout this [branch](https://github.com/epicshaggy/apple-sign-in/tree/android) which tries to implement android use, but I did not complete it for these [reasons](https://github.com/capacitor-community/apple-sign-in/issues/15#issuecomment-771663344).  Currently I have a custom implementation on my app which sends the post request to my backend service.
