### ISSUE TITLE
How to prevent "registerWebPlugin" for iOS?

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/apple-sign-in#31]
So the docs say we need to execute 
```js
registerWebPlugin(SignInWithApple);
```
but is this only for the web?

If the user uses the plugin on iOS capacitor app, what is the recommended way to not execute `registerWebPlugin(SignInWithApple);` for that case?

`getDeviceInfo` is async, so it's not ideal right?

**Comment by mirko77** [comment]
I usually access getDeviceInfo when bootstrapping the app and save it in a global object I can access whenever I need.

**Comment by cyril-colin** [comment]
In order to avoid the `registerWebPlugin(SignInWithApple);` I just import the module (that already make this call, only on web environment due to capacitor mecanism : 

```typescript
import '@capacitor-community/apple-sign-in'; // This call avoid needs to call registerWebPlugin
import {
    SignInWithAppleResponse,
    SignInWithAppleOptions,
} from '@capacitor-community/apple-sign-in';
import {Plugins} from '@capacitor/core';
```

Hope this helps !
