### ISSUE TITLE
Cant resolve scriptjs

### ISSUE THREAD

**Issue by lucasrleandro** [capacitor-community/apple-sign-in#35]
Hi, 

I installed the package and imported it (just like the docs). But when I get this error in compilation...

ERROR in ./node_modules/@capacitor-community/apple-sign-in/dist/esm/web.js
Module not found: Error: Can't resolve 'scriptjs' in '/Users/***/node_modules/@capacitor-community/apple-sign-in/dist/esm'
[ERROR] An error occurred while running subprocess ng.

**Comment by lucasrleandro** [comment]
Removed the registerWebPlugin, since i only use it on iOS. 
Still get the error when building --prod.
Then i commented the following lines on "apple-sign-in/dist/esm/web.js"

const script = require("scriptjs");
script(this.appleScriptUrl, () => resolve(true));

Now it compiles and works in development device.

**Comment by cyril-colin** [comment]
To make it works, I have added scriptjs to my main project with `npm install scriptjs`

**Comment by epicshaggy** [comment]
resolved in #20
