### ISSUE TITLE
Capacitor version error with v1.0.0

### ISSUE THREAD

**Issue by Exocomp** [capacitor-community/apple-sign-in#43]
Version 1.0.0 has the wrong build target, it is configured for 11.0 but Capacitor 3 requires 12.0, resulting in the following error:

`Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0`

Looks like the issue has been resolved in the master, can a new version be deployed to npm.

**Comment by Exocomp** [comment]
I'm confused with the versioning, I see 0.1.2 is the latest in npm which is a lesser version than 1.0.0 however, is 0.1.2 on master and has the latest?

**Comment by grallc** [comment]
Hi,
Same issue here.
Have you figured this out ?

**Comment by Exocomp** [comment]
@grallc I'm using @capacitor-community/apple-sign-in perhaps our issues are different

**Comment by svrakata** [comment]
I have the same problem. `Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0`. Any ideas?

**Comment by rdlabo** [comment]
@svrakata  This may not plugin error. currency version is be for iOS 12.0:
https://github.com/capacitor-community/apple-sign-in/blob/master/ios/Podfile#L1
https://github.com/capacitor-community/apple-sign-in/blob/master/CapacitorCommunityAppleSignIn.podspec#L14

And I'm using this plugin with Capacitor 3.

**Comment by svrakata** [comment]
@rdlabo 
Thank you! Will try that.

**Comment by jcesarmobile** [comment]
There has been a mixup of versions, latest version (0.1.2) was compatible with Capacitor 3 already, while version 1.0.0 wasn't, not sure why it was published with a major version bump 8 months ago and then continued doing patch/minor bumps from 0.x.x

I've published 1.0.1 with latest changes
