### ISSUE TITLE
Can't find module @capacitor-community/apple-sign-in with Capacitor 3

### ISSUE THREAD

**Issue by eduboxgithub** [capacitor-community/apple-sign-in#45]
**Describe the bug**
I'm upgrading and app from Capacitor 2.0 to Capacitor 3.0.

The last plugin that needs to be migrated is this one.

I tried to update to the latest version with no luck.

How can I install the latest version compatible with Capacitor 3?

In the repo there's a 1.0.0 release, but the latest npm release is version 0.1.2.
I also tried to install directly from GitHub, npm install capacitor-community/apple-sign-in but I always get an error:

./src/app/services/authentication.service.ts:11:0-69 - Error: Module not found: Error: Can't resolve '@capacitor-community/apple-sign-in' in 'D:\_git\MyApp\MyApp\src\app\services'       
[ng] Error: src/app/services/authentication.service.ts:12:82 - error TS2307: Cannot find module '@capacitor-community/apple-sign-in' or its corresponding type declarations.
[ng] 12 import { SignInWithApple, SignInWithAppleResponse, SignInWithAppleOptions } from '@capacitor-community/apple-sign-in';

**Screenshots**
![image](https://user-images.githubusercontent.com/13800439/127660012-d9c8bb05-c74c-4466-b5d2-f4718925cd4f.png)

How can I successfully install and use this plugin with Capacitor 3.0?

**Comment by eduboxgithub** [comment]
Any guesses what the problem might be?

Only this plugin is missing to complete my app migration to Capacitor 3. At the moment, I don't know which version to install.

There doesn't seem to exist a version in npm compatible with Capacitor 3.

**Comment by pamontep** [comment]
> Any guesses what the problem might be?
> 
> Only this plugin is missing to complete my app migration to Capacitor 3. At the moment, I don't know which version to install.
> 
> There doesn't seem to exist a version in npm compatible with Capacitor 3.

I also found this issue. Any update on this?

**Comment by selected-pixel-jameson** [comment]
Yeah. What's going on with this?

**Comment by selected-pixel-jameson** [comment]
Why has support for Capacitor 3 not been released? This is literally the only plugin that I have that isn't supporting capacitor 3 right now.

**Comment by jcesarmobile** [comment]
There has been a mixup of versions, latest version (0.1.2) was compatible with Capacitor 3 already, while version 1.0.0 wasn't, not sure why it was published with a major version bump 8 months ago and then continued doing patch/minor bumps from 0.x.x

I've published 1.0.1 with latest changes
