### ISSUE TITLE
Uses non-standard Capitalisation for the API

### ISSUE THREAD

**Issue by chrisweight** [capacitor-community/apple-sign-in#5]
The plugin exposes a `.Authorize()`method, this is Capitalised and thus non-standard, it might be useful to rename it to `.authorize()` to keep it standardised. This would necessitate a major-version bump as it's a breaking change.

**Comment by mlynch** [comment]
Agreed these should all be lowercased

**Comment by chrisweight** [comment]
Dealt with in #18
