### ISSUE TITLE
Issue with Capacitor 2.5 and apple-sign-in 1.x

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/apple-sign-in#51]
I know you started work on Capacitor 3 compatibility, and you put that work on the master branch.

There is however a small issue with the way the package.json was written for this package's version `1.0.0`.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3253920/132648587-89fc31b6-12e4-4b0d-b3e0-6d5f10683aaa.png">

↑
 I can't install it any more on a Capacitor 2.x project...

I made a fix and want to open a PR:

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3253920/132648443-e02c90c8-64a1-4e58-ae2e-da07d22abff3.png">

However, the version `1.0.0` version of `apple-sign-in` doesn't have a branch any more, so I can't make the PR towards anything.

Please help!

**Comment by jcesarmobile** [comment]
I've published 0.2.0 that should be compatible with Capacitor 2, and 1.0.1 that should be compatible with Capacitor 3
Also created 0.x branch in case somebody want to make changes for Capacitor 2
