### ISSUE TITLE
iOS redirectURI

### ISSUE THREAD

**Issue by GeekChorus** [capacitor-community/apple-sign-in#59]
I have no idea what to do to get this to work in iOS and Capacitor 2.0.  It appears I have to include the redirectURI otherwise nothing happens when I invoke authorize. And yet if I include something (which is inevitably incorrect as this is an app, not a website) the app opens an external browser to report "Invalid URI".  I'm so desperate, I'd Venmo someone a thank you if I could get this up and running.

**Comment by LeCoupa** [comment]
Have you found a solution for this?
