### ISSUE TITLE
Update for Capacitor v4 support; fix dependency tree conflict

### ISSUE THREAD

**Issue by yllaw** [capacitor-community/apple-sign-in#79]
Capacitor 4 has been officially released. There are a few community plugins that use Capacitor 3.0 packages as dependencies. This causes an error when migrating to v4 due to npm dependency tree conflicts (v3 cli, etc.).;

The solution here is to update the plugin to have[ capacitor v4 support.](https://capacitorjs.com/docs/updating/4-0) 

Thanks

**Comment by yllaw** [comment]
Hello again,

Thanks for upgrading the solution to have v4 support per pre-release version to 4.0.0-0.

As it is a pre-release, I'd like to know what else needs to be implemented for the official npm version  4.0.0 release. 

NOTE: We are currently using 4.0.0-0 in production.

Thanks again

**Comment by hallbird** [comment]
hello, 

I think I have issue for this, as I am trying to install am getting this error 

npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor-community/apple-sign-in@1.0.1

https://ibb.co/DWPPKmm

**Comment by yllaw** [comment]
@hallbird 

There is a prerelease npm package version 4.0.0-0 that will fix this.

Try
`npm i @capacitor-community/apple-sign-in@4.0.0-0`

Unfortunately the official release does not support Capacitor v4 yet. Currently the only workaround is to use prerelease version 4.0.0-0.

**Comment by reslear** [comment]
hi, I join to testing

**Comment by hallbird** [comment]
> @hallbird
> 
> There is a prerelease npm package version 4.0.0-0 that will fix this.
> 
> Try `npm i @capacitor-community/apple-sign-in@4.0.0-0`
> 
> Unfortunately the official release does not support Capacitor v4 yet. Currently the only workaround is to use prerelease version 4.0.0-0.
> 
> NOTE: You may have to delete `package-lock.json` file and `node_modules` folder before running `npm install` for the package to update correctly.

Thank you, did work for me

**Comment by jcesarmobile** [comment]
I've published 4.0.0 as latest
