### ISSUE TITLE
No Exported Member

### ISSUE THREAD

**Issue by iconio** [capacitor-community/apple-sign-in#8]
**Describe the bug**
There is a compilation error after the installation of the plugin using Ionic 5 with Angular.
``
error TS2305: Module '"../../../node_modules/@capacitor-community/apple-sign-in/dist/esm"' has no exported member 'ResponseSignInWithApplePlugin'.
14 import { ResponseSignInWithApplePlugin } from '@capacitor-community/apple-sign-in';
```

**To Reproduce**
Steps to reproduce the behavior:
Added the plugin exactly like description.

**Expected behavior**
To compile with no errors.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.5.1
 - Ionic 5

**Comment by mlynch** [comment]
I think you're using an old version, that wasn't released yet
