### ISSUE TITLE
Issue in android build

### ISSUE THREAD

**Issue by junaid5546** [capacitor-community/apple-sign-in#95]
I am trying to build android as I am using Apple Signin for ios only
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
    namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

**Comment by junaid5546** [comment]
Kindly help me out.

**Comment by jcesarmobile** [comment]
Update to version 5.0.0 of the plugin, it was released with the namespace.
